### ISSUE TITLE
Doesn't compile with latest version of HandyFrame

### ISSUE THREAD

**Issue by ugochirico** [casatwy/CTVideoPlayerView#32]
I added CTVideoPlayer to my pod file and I typed pod update
pod update installed HandyFrame too
When I compile my project I got several syntax error due to properties that in HandyFrame has different name.
For example
CGFloat centerX = self.playButton.centerX;
gives syntax error because the correct name is ct_centerX instead of centerX

Can you update against the latest version of HandyFrame?

**Comment by casatwy** [comment]
sorry!

I am not at front of a computer now, you can use handyframe 1.1.2 ...

Send from my iPhone

在 2017年5月8日，下午6:27，Ugo Chirico <notifications@github.com<mailto:notifications@github.com>> 写道：


I added CTVideoPlayer to my pod file and I typed pod update
pod update installed HandyFrame too
When I compile my project I got several syntax error due to properties that in HandyFrame has different name.
For example
CGFloat centerX = self.playButton.centerX;
gives syntax error because the correct name is ct_centerX instead of centerX

Can you update against the latest version of HandyFrame?

**Comment by casatwy** [comment]
I have fixed this, Thank you for your mention!
